export const BAGS = [
  {
    min: 12,
    max: 14,
    season: 'Winter',
    bag: 'Cosy 3.5 tog bag',
    clothes: 'Cotton Bodysuit + Sleepsuit',
    css: 'colour-purple',
  },
  {
    min: 15,
    max: 16,
    season: 'Winter',
    bag: 'Regular 2.5 tog bag',
    clothes: 'Cotton Bodysuit + Sleepsuit + Blanket',
    css: 'colour-blue',
  },
  {
    min: 17,
    max: 19,
    season: 'All except warm summer',
    bag: 'Regular 2.5 tog bag',
    clothes: 'Cotton Bodysuit + Sleepsuit',
    css: 'colour-green',
  },
  {
    min: 20,
    max: 21,
    season: 'All except warm summer',
    bag: 'Regular 2.5 tog bag',
    clothes: 'Cotton Sleepsuit',
    css: 'colour-yellow',
  },
  {
    min: 22,
    max: 25,
    season: 'Summer and daytime naps',
    bag: 'Lightweight 1.5 tog bag',
    clothes: 'Cotton Bodysuit',
    css: 'colour-orange',
  },
  {
    min: 25,
    max: Infinity,
    season: 'High summer or hot countries',
    bag: 'Under 1 tog sheet',
    clothes: 'Cotton Body suit',
    css: 'colour-red',
  },
];